# Generated by Django 3.0.4 on 2020-03-27 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 27, 13, 10, 52, 193126, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='format',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
